/*
 * Copyright 2018 Fluence Labs Limited
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package proto3.tendermint

@SerialVersionUID(0L)
final case class Data(
  txs: _root_.scala.collection.Seq[_root_.com.google.protobuf.ByteString] = _root_.scala.collection.Seq.empty
) extends scalapb.GeneratedMessage with scalapb.Message[Data] with scalapb.lenses.Updatable[Data] {

  @transient
  private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
  private[this] def __computeSerializedValue(): _root_.scala.Int = {
    var __size = 0
    txs.foreach { __item =>
      val __value = __item
      __size += _root_.com.google.protobuf.CodedOutputStream.computeBytesSize(1, __value)
    }
    __size
  }
  final override def serializedSize: _root_.scala.Int = {
    var read = __serializedSizeCachedValue
    if (read == 0) {
      read = __computeSerializedValue()
      __serializedSizeCachedValue = read
    }
    read
  }

  def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
    txs.foreach { __v =>
      val __m = __v
      _output__.writeBytes(1, __m)
    };
  }

  def mergeFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): proto3.tendermint.Data = {
    val __txs = (_root_.scala.collection.immutable.Vector
      .newBuilder[_root_.com.google.protobuf.ByteString] ++= this.txs)
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __txs += _input__.readBytes()
        case tag => _input__.skipField(tag)
      }
    }
    proto3.tendermint.Data(
      txs = __txs.result()
    )
  }
  def clearTxs = copy(txs = _root_.scala.collection.Seq.empty)
  def addTxs(__vs: _root_.com.google.protobuf.ByteString*): Data = addAllTxs(__vs)
  def addAllTxs(__vs: TraversableOnce[_root_.com.google.protobuf.ByteString]): Data = copy(txs = txs ++ __vs)
  def withTxs(__v: _root_.scala.collection.Seq[_root_.com.google.protobuf.ByteString]): Data = copy(txs = __v)

  def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
    (__fieldNumber: @ _root_.scala.unchecked) match {
      case 1 => txs
    }
  }

  def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
    _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
    (__field.number: @ _root_.scala.unchecked) match {
      case 1 =>
        _root_.scalapb.descriptors
          .PRepeated(txs.map(_root_.scalapb.descriptors.PByteString)(_root_.scala.collection.breakOut))
    }
  }
  def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
  def companion = proto3.tendermint.Data
}

object Data extends scalapb.GeneratedMessageCompanion[proto3.tendermint.Data] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[proto3.tendermint.Data] = this

  def fromFieldsMap(
    __fieldsMap: scala.collection.immutable.Map[
      _root_.com.google.protobuf.Descriptors.FieldDescriptor,
      _root_.scala.Any
    ]
  ): proto3.tendermint.Data = {
    _root_.scala.Predef.require(
      __fieldsMap.keys.forall(_.getContainingType() == javaDescriptor),
      "FieldDescriptor does not match message type."
    )
    val __fields = javaDescriptor.getFields
    proto3.tendermint.Data(
      __fieldsMap
        .getOrElse(__fields.get(0), Nil)
        .asInstanceOf[_root_.scala.collection.Seq[_root_.com.google.protobuf.ByteString]]
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[proto3.tendermint.Data] =
    _root_.scalapb.descriptors.Reads {
      case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
        _root_.scala.Predef.require(
          __fieldsMap.keys.forall(_.containingMessage == scalaDescriptor),
          "FieldDescriptor does not match message type."
        )
        proto3.tendermint.Data(
          __fieldsMap
            .get(scalaDescriptor.findFieldByNumber(1).get)
            .map(_.as[_root_.scala.collection.Seq[_root_.com.google.protobuf.ByteString]])
            .getOrElse(_root_.scala.collection.Seq.empty)
        )
      case _ => throw new RuntimeException("Expected PMessage")
    }

  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor =
    TendermintProto.javaDescriptor.getMessageTypes.get(5)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = TendermintProto.scalaDescriptor.messages(5)

  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] =
    throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_]] = Seq.empty

  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] =
    throw new MatchError(__fieldNumber)
  lazy val defaultInstance = proto3.tendermint.Data(
    )
  implicit class DataLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, proto3.tendermint.Data])
      extends _root_.scalapb.lenses.ObjectLens[UpperPB, proto3.tendermint.Data](_l) {

    def txs: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.collection.Seq[_root_.com.google.protobuf.ByteString]] =
      field(_.txs)((c_, f_) => c_.copy(txs = f_))
  }
  final val TXS_FIELD_NUMBER = 1
}
