/** Declaration file generated by dts-gen */

declare module "ethereum-event-logs"
{
    export function parseLog(logs: any, eventAbis: any, ...args: any[]): any;

    export namespace parseLog {
        const prototype: {};

    }
}
