/** Declaration file generated by dts-gen */
declare module 'js-sha1' {

    export = js_sha1;

    declare function js_sha1(message: string | ArrayBuffer): string;

    declare namespace js_sha1 {
        function array(message: string | ArrayBuffer): number[];

        function arrayBuffer(message: string | ArrayBuffer): ArrayBuffer;

        function create(): any;

        function digest(message: string | ArrayBuffer): number[];

        function hex(message: string | ArrayBuffer): string;

        function update(message: string | ArrayBuffer): any;

    }
}
