{
 "title": "nox stats",
 "tags": [ "nox" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "env",
    "query": {
     "query": "label_values(up{job=~\"fluence|rust-peer|nox\"}, env)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(up{job=~\"fluence|rust-peer|nox\", env=~\"$env\"}, instance)"
    }
   },
   {
    "name": "particle_type",
    "query": {
     "query": "label_values(connection_pool_particle_sizes_bucket{env=\"$env\"}, particle_type)"
    }
   },
   { "name": "timerange", "query": "1d,7d,30d" }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nox versions",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "nox_build_info{env=~\"$env\",instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$env status",
   "type": "status-history",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 8 },
   "repeat": "env",
   "targets": [
    {
     "expr": "avg_over_time((1 - up{job=~\"fluence|rust-peer|nox\",env=~\"$env\",instance=~\"$instance\"})[5m:])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "Connections $env", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }, "repeat": "env" },
  {
   "title": "Active Connections",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "connection_pool_connected_peers{env=~\"$env\",instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "sum(connection_pool_connected_peers{env=\"$env\",instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Particles $env",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "repeat": "env",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Particles per $timerange",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
     "repeat": "timerange",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (increase(connectivity_particle_send_success_total{env=\"$env\",instance=~\"$instance\"}[$timerange]))",
       "legendFormat": "sent"
      },
      {
       "expr": "sum(increase(connection_pool_received_particles_total{env=\"$env\",instance=~\"$instance\"}[$timerange]))",
       "legendFormat": "received"
      }
     ]
    },
    {
     "title": "Particles per second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "-sum by (env) (rate(connectivity_particle_send_success_total{env=\"$env\"}[$__rate_interval]))",
       "legendFormat": "{{ env }} sent"
      },
      {
       "expr": "sum by (env) (rate(connection_pool_received_particles_total{env=\"$env\"}[$__rate_interval]))",
       "legendFormat": "{{ env }} received"
      }
     ]
    },
    {
     "title": "Particles sent success ($particle_type)",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
     "repeat": "particle_type",
     "targets": [
      {
       "expr": "increase(connectivity_particle_send_success_total{env=\"$env\",instance=~\"$instance\",particle_type=\"$particle_type\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Particle Send Failures ($particle_type)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
     "repeat": "particle_type",
     "targets": [
      {
       "expr": "increase(connectivity_particle_send_failure_total{env=\"$env\",instance=~\"$instance\",particle_type=\"$particle_type\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Incoming Particle Sizes ($particle_type)",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 63 },
     "repeat": "particle_type",
     "targets": [
      {
       "expr": "sum(increase(connection_pool_particle_sizes_bucket{env=~\"$env\",particle_type=\"$particle_type\"}[$__rate_interval])) by (le)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Alive Actors",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 73 },
     "targets": [
      {
       "expr": "particle_executor_alive_actors{env=~\"$env\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Connection Pool Queue Size",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 73 },
     "targets": [
      {
       "expr": "connection_pool_particle_queue_size{env=~\"$env\"} >= 0",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Actor mailbox size",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 73 },
     "targets": [
      {
       "expr": "particle_executor_total_actors_mailbox{env=~\"$env\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Execution Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Interpretation time",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 82 },
     "targets": [
      {
       "expr": "sum(increase(particle_executor_interpretation_time_sec_bucket{env=~\"$env\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Service call time",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 92 },
     "targets": [
      {
       "expr": "sum(increase(particle_executor_service_call_time_sec_bucket{env=~\"$env\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Service Calls",
     "type": "stat",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 102 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (env) (particle_executor_service_call_success_total{env=\"$env\", instance=~\"$instance\"})",
       "legendFormat": "success"
      },
      {
       "expr": "sum by (env) (particle_executor_service_call_failure_total{env=\"$env\", instance=~\"$instance\"})",
       "legendFormat": "failure"
      }
     ]
    },
    {
     "title": "Service Calls per second",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 11, "x": 5, "y": 102 },
     "targets": [
      {
       "expr": "sum by (instance) (rate(particle_executor_service_call_time_sec_count{env=\"$env\",instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Service Call Failures",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 102 },
     "targets": [
      {
       "expr": "increase(particle_executor_service_call_failure_total{env=~\"$env\",instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Interpolation",
     "type": "stat",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (env) (particle_executor_interpretation_successes_total{env=\"$env\", instance=~\"$instance\"})",
       "legendFormat": "success"
      },
      {
       "expr": "sum by (env) (particle_executor_interpretation_failures_total{env=\"$env\", instance=~\"$instance\"})",
       "legendFormat": "failure"
      }
     ]
    },
    {
     "title": "Interpretations per second",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 11, "x": 5, "y": 110 },
     "targets": [
      {
       "expr": "sum by (instance) (rate(particle_executor_interpretation_time_sec_count{env=~\"$env\",instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Interpretation Failures",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 110 },
     "targets": [
      {
       "expr": "increase(particle_executor_interpretation_failures_total{env=~\"$env\",instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "AquaVM stats $env",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "repeat": "env",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Single AquaVM memory max",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 119 },
     "targets": [
      {
       "expr": "aqua_vm_pool_vm_mem_max{env=~\"$env\"}",
       "legendFormat": "{{ instance }} max"
      }
     ]
    },
    {
     "title": "AquaVM total memory",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 119 },
     "targets": [
      {
       "expr": "aqua_vm_pool_vm_mem_total{env=\"$env\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "AquaVM Pool Starvation",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 127 },
     "targets": [
      {
       "expr": "irate(aqua_vm_pool_no_free_vm_total{env=\"$env\"}[$__rate_interval])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Busy AquaVMs",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 9, "x": 6, "y": 127 },
     "targets": [
      {
       "expr": "aqua_vm_pool_get_vm_total{env=\"$env\"} - aqua_vm_pool_put_vm_total{env=\"$env\"} - aqua_vm_pool_no_free_vm_total{env=\"$env\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Busy AquaVMs (misbehaves ???)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 127 },
     "targets": [
      {
       "expr": "aqua_vm_pool_pool_size{env=\"$env\"} - aqua_vm_pool_free_vms{env=\"$env\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "put_vm per second",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 135 },
     "targets": [
      {
       "expr": "irate(aqua_vm_pool_put_vm_total{env=~\"$env\"}[$__rate_interval])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "get_vm per second",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 135 },
     "targets": [
      {
       "expr": "irate(aqua_vm_pool_get_vm_total{env=~\"$env\"}[$__rate_interval])",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  }
 ]
}