/*
 * Copyright 2018 Fluence Labs Limited
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package proto3.tendermint

@SerialVersionUID(0L)
final case class Block(
  header: _root_.scala.Option[proto3.tendermint.Header] = None,
  data: _root_.scala.Option[proto3.tendermint.Data] = None,
  evidence: _root_.scala.Option[proto3.tendermint.EvidenceData] = None,
  lastCommit: _root_.scala.Option[proto3.tendermint.Commit] = None
) extends scalapb.GeneratedMessage with scalapb.Message[Block] with scalapb.lenses.Updatable[Block] {

  @transient
  private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
  private[this] def __computeSerializedValue(): _root_.scala.Int = {
    var __size = 0
    if (header.isDefined) {
      val __value = header.get
      __size += 1 + _root_.com.google.protobuf.CodedOutputStream
        .computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
    };
    if (data.isDefined) {
      val __value = data.get
      __size += 1 + _root_.com.google.protobuf.CodedOutputStream
        .computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
    };
    if (evidence.isDefined) {
      val __value = evidence.get
      __size += 1 + _root_.com.google.protobuf.CodedOutputStream
        .computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
    };
    if (lastCommit.isDefined) {
      val __value = lastCommit.get
      __size += 1 + _root_.com.google.protobuf.CodedOutputStream
        .computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
    };
    __size
  }
  final override def serializedSize: _root_.scala.Int = {
    var read = __serializedSizeCachedValue
    if (read == 0) {
      read = __computeSerializedValue()
      __serializedSizeCachedValue = read
    }
    read
  }

  def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
    header.foreach { __v =>
      val __m = __v
      _output__.writeTag(1, 2)
      _output__.writeUInt32NoTag(__m.serializedSize)
      __m.writeTo(_output__)
    };
    data.foreach { __v =>
      val __m = __v
      _output__.writeTag(2, 2)
      _output__.writeUInt32NoTag(__m.serializedSize)
      __m.writeTo(_output__)
    };
    evidence.foreach { __v =>
      val __m = __v
      _output__.writeTag(3, 2)
      _output__.writeUInt32NoTag(__m.serializedSize)
      __m.writeTo(_output__)
    };
    lastCommit.foreach { __v =>
      val __m = __v
      _output__.writeTag(4, 2)
      _output__.writeUInt32NoTag(__m.serializedSize)
      __m.writeTo(_output__)
    };
  }

  def mergeFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): proto3.tendermint.Block = {
    var __header = this.header
    var __data = this.data
    var __evidence = this.evidence
    var __lastCommit = this.lastCommit
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __header = Option(
            _root_.scalapb.LiteParser
              .readMessage(_input__, __header.getOrElse(proto3.tendermint.Header.defaultInstance))
          )
        case 18 =>
          __data = Option(
            _root_.scalapb.LiteParser.readMessage(_input__, __data.getOrElse(proto3.tendermint.Data.defaultInstance))
          )
        case 26 =>
          __evidence = Option(
            _root_.scalapb.LiteParser
              .readMessage(_input__, __evidence.getOrElse(proto3.tendermint.EvidenceData.defaultInstance))
          )
        case 34 =>
          __lastCommit = Option(
            _root_.scalapb.LiteParser
              .readMessage(_input__, __lastCommit.getOrElse(proto3.tendermint.Commit.defaultInstance))
          )
        case tag => _input__.skipField(tag)
      }
    }
    proto3.tendermint.Block(
      header = __header,
      data = __data,
      evidence = __evidence,
      lastCommit = __lastCommit
    )
  }
  def getHeader: proto3.tendermint.Header = header.getOrElse(proto3.tendermint.Header.defaultInstance)
  def clearHeader: Block = copy(header = None)
  def withHeader(__v: proto3.tendermint.Header): Block = copy(header = Option(__v))
  def getData: proto3.tendermint.Data = data.getOrElse(proto3.tendermint.Data.defaultInstance)
  def clearData: Block = copy(data = None)
  def withData(__v: proto3.tendermint.Data): Block = copy(data = Option(__v))
  def getEvidence: proto3.tendermint.EvidenceData = evidence.getOrElse(proto3.tendermint.EvidenceData.defaultInstance)
  def clearEvidence: Block = copy(evidence = None)
  def withEvidence(__v: proto3.tendermint.EvidenceData): Block = copy(evidence = Option(__v))
  def getLastCommit: proto3.tendermint.Commit = lastCommit.getOrElse(proto3.tendermint.Commit.defaultInstance)
  def clearLastCommit: Block = copy(lastCommit = None)
  def withLastCommit(__v: proto3.tendermint.Commit): Block = copy(lastCommit = Option(__v))

  def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
    (__fieldNumber: @ _root_.scala.unchecked) match {
      case 1 => header.orNull
      case 2 => data.orNull
      case 3 => evidence.orNull
      case 4 => lastCommit.orNull
    }
  }

  def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
    _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
    (__field.number: @ _root_.scala.unchecked) match {
      case 1 => header.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
      case 2 => data.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
      case 3 => evidence.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
      case 4 => lastCommit.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
    }
  }
  def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
  def companion = proto3.tendermint.Block
}

object Block extends scalapb.GeneratedMessageCompanion[proto3.tendermint.Block] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[proto3.tendermint.Block] = this

  def fromFieldsMap(
    __fieldsMap: scala.collection.immutable.Map[
      _root_.com.google.protobuf.Descriptors.FieldDescriptor,
      _root_.scala.Any
    ]
  ): proto3.tendermint.Block = {
    _root_.scala.Predef.require(
      __fieldsMap.keys.forall(_.getContainingType() == javaDescriptor),
      "FieldDescriptor does not match message type."
    )
    val __fields = javaDescriptor.getFields
    proto3.tendermint.Block(
      __fieldsMap.get(__fields.get(0)).asInstanceOf[_root_.scala.Option[proto3.tendermint.Header]],
      __fieldsMap.get(__fields.get(1)).asInstanceOf[_root_.scala.Option[proto3.tendermint.Data]],
      __fieldsMap.get(__fields.get(2)).asInstanceOf[_root_.scala.Option[proto3.tendermint.EvidenceData]],
      __fieldsMap.get(__fields.get(3)).asInstanceOf[_root_.scala.Option[proto3.tendermint.Commit]]
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[proto3.tendermint.Block] =
    _root_.scalapb.descriptors.Reads {
      case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
        _root_.scala.Predef.require(
          __fieldsMap.keys.forall(_.containingMessage == scalaDescriptor),
          "FieldDescriptor does not match message type."
        )
        proto3.tendermint.Block(
          __fieldsMap
            .get(scalaDescriptor.findFieldByNumber(1).get)
            .flatMap(_.as[_root_.scala.Option[proto3.tendermint.Header]]),
          __fieldsMap
            .get(scalaDescriptor.findFieldByNumber(2).get)
            .flatMap(_.as[_root_.scala.Option[proto3.tendermint.Data]]),
          __fieldsMap
            .get(scalaDescriptor.findFieldByNumber(3).get)
            .flatMap(_.as[_root_.scala.Option[proto3.tendermint.EvidenceData]]),
          __fieldsMap
            .get(scalaDescriptor.findFieldByNumber(4).get)
            .flatMap(_.as[_root_.scala.Option[proto3.tendermint.Commit]])
        )
      case _ => throw new RuntimeException("Expected PMessage")
    }

  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor =
    TendermintProto.javaDescriptor.getMessageTypes.get(6)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = TendermintProto.scalaDescriptor.messages(6)

  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @ _root_.scala.unchecked) match {
      case 1 => __out = proto3.tendermint.Header
      case 2 => __out = proto3.tendermint.Data
      case 3 => __out = proto3.tendermint.EvidenceData
      case 4 => __out = proto3.tendermint.Commit
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_]] = Seq.empty

  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] =
    throw new MatchError(__fieldNumber)
  lazy val defaultInstance = proto3.tendermint.Block(
    )
  implicit class BlockLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, proto3.tendermint.Block])
      extends _root_.scalapb.lenses.ObjectLens[UpperPB, proto3.tendermint.Block](_l) {

    def header: _root_.scalapb.lenses.Lens[UpperPB, proto3.tendermint.Header] =
      field(_.getHeader)((c_, f_) => c_.copy(header = Option(f_)))

    def optionalHeader: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[proto3.tendermint.Header]] =
      field(_.header)((c_, f_) => c_.copy(header = f_))

    def data: _root_.scalapb.lenses.Lens[UpperPB, proto3.tendermint.Data] =
      field(_.getData)((c_, f_) => c_.copy(data = Option(f_)))

    def optionalData: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[proto3.tendermint.Data]] =
      field(_.data)((c_, f_) => c_.copy(data = f_))

    def evidence: _root_.scalapb.lenses.Lens[UpperPB, proto3.tendermint.EvidenceData] =
      field(_.getEvidence)((c_, f_) => c_.copy(evidence = Option(f_)))

    def optionalEvidence: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[proto3.tendermint.EvidenceData]] =
      field(_.evidence)((c_, f_) => c_.copy(evidence = f_))

    def lastCommit: _root_.scalapb.lenses.Lens[UpperPB, proto3.tendermint.Commit] =
      field(_.getLastCommit)((c_, f_) => c_.copy(lastCommit = Option(f_)))

    def optionalLastCommit: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[proto3.tendermint.Commit]] =
      field(_.lastCommit)((c_, f_) => c_.copy(lastCommit = f_))
  }
  final val HEADER_FIELD_NUMBER = 1
  final val DATA_FIELD_NUMBER = 2
  final val EVIDENCE_FIELD_NUMBER = 3
  final val LAST_COMMIT_FIELD_NUMBER = 4
}
