/*
 * Copyright 2018 Fluence Labs Limited
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package proto3.tendermint

@SerialVersionUID(0L)
final case class Commit(
  blockId: _root_.scala.Option[proto3.tendermint.BlockID] = None,
  precommits: _root_.com.google.protobuf.ByteString = _root_.com.google.protobuf.ByteString.EMPTY
) extends scalapb.GeneratedMessage with scalapb.Message[Commit] with scalapb.lenses.Updatable[Commit] {

  @transient
  private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
  private[this] def __computeSerializedValue(): _root_.scala.Int = {
    var __size = 0
    if (blockId.isDefined) {
      val __value = blockId.get
      __size += 1 + _root_.com.google.protobuf.CodedOutputStream
        .computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
    };

    {
      val __value = precommits
      if (__value != _root_.com.google.protobuf.ByteString.EMPTY) {
        __size += _root_.com.google.protobuf.CodedOutputStream.computeBytesSize(2, __value)
      }
    };
    __size
  }
  final override def serializedSize: _root_.scala.Int = {
    var read = __serializedSizeCachedValue
    if (read == 0) {
      read = __computeSerializedValue()
      __serializedSizeCachedValue = read
    }
    read
  }

  def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
    blockId.foreach { __v =>
      val __m = __v
      _output__.writeTag(1, 2)
      _output__.writeUInt32NoTag(__m.serializedSize)
      __m.writeTo(_output__)
    };
    {
      val __v = precommits
      if (__v != _root_.com.google.protobuf.ByteString.EMPTY) {
        _output__.writeBytes(2, __v)
      }
    };
  }

  def mergeFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): proto3.tendermint.Commit = {
    var __blockId = this.blockId
    var __precommits = this.precommits
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __blockId = Option(
            _root_.scalapb.LiteParser
              .readMessage(_input__, __blockId.getOrElse(proto3.tendermint.BlockID.defaultInstance))
          )
        case 18 =>
          __precommits = _input__.readBytes()
        case tag => _input__.skipField(tag)
      }
    }
    proto3.tendermint.Commit(
      blockId = __blockId,
      precommits = __precommits
    )
  }
  def getBlockId: proto3.tendermint.BlockID = blockId.getOrElse(proto3.tendermint.BlockID.defaultInstance)
  def clearBlockId: Commit = copy(blockId = None)
  def withBlockId(__v: proto3.tendermint.BlockID): Commit = copy(blockId = Option(__v))
  def withPrecommits(__v: _root_.com.google.protobuf.ByteString): Commit = copy(precommits = __v)

  def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
    (__fieldNumber: @ _root_.scala.unchecked) match {
      case 1 => blockId.orNull
      case 2 => {
        val __t = precommits
        if (__t != _root_.com.google.protobuf.ByteString.EMPTY) __t else null
      }
    }
  }

  def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
    _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
    (__field.number: @ _root_.scala.unchecked) match {
      case 1 => blockId.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
      case 2 => _root_.scalapb.descriptors.PByteString(precommits)
    }
  }
  def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
  def companion = proto3.tendermint.Commit
}

object Commit extends scalapb.GeneratedMessageCompanion[proto3.tendermint.Commit] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[proto3.tendermint.Commit] = this

  def fromFieldsMap(
    __fieldsMap: scala.collection.immutable.Map[
      _root_.com.google.protobuf.Descriptors.FieldDescriptor,
      _root_.scala.Any
    ]
  ): proto3.tendermint.Commit = {
    _root_.scala.Predef.require(
      __fieldsMap.keys.forall(_.getContainingType() == javaDescriptor),
      "FieldDescriptor does not match message type."
    )
    val __fields = javaDescriptor.getFields
    proto3.tendermint.Commit(
      __fieldsMap.get(__fields.get(0)).asInstanceOf[_root_.scala.Option[proto3.tendermint.BlockID]],
      __fieldsMap
        .getOrElse(__fields.get(1), _root_.com.google.protobuf.ByteString.EMPTY)
        .asInstanceOf[_root_.com.google.protobuf.ByteString]
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[proto3.tendermint.Commit] =
    _root_.scalapb.descriptors.Reads {
      case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
        _root_.scala.Predef.require(
          __fieldsMap.keys.forall(_.containingMessage == scalaDescriptor),
          "FieldDescriptor does not match message type."
        )
        proto3.tendermint.Commit(
          __fieldsMap
            .get(scalaDescriptor.findFieldByNumber(1).get)
            .flatMap(_.as[_root_.scala.Option[proto3.tendermint.BlockID]]),
          __fieldsMap
            .get(scalaDescriptor.findFieldByNumber(2).get)
            .map(_.as[_root_.com.google.protobuf.ByteString])
            .getOrElse(_root_.com.google.protobuf.ByteString.EMPTY)
        )
      case _ => throw new RuntimeException("Expected PMessage")
    }

  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor =
    TendermintProto.javaDescriptor.getMessageTypes.get(7)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = TendermintProto.scalaDescriptor.messages(7)

  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @ _root_.scala.unchecked) match {
      case 1 => __out = proto3.tendermint.BlockID
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_]] = Seq.empty

  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] =
    throw new MatchError(__fieldNumber)
  lazy val defaultInstance = proto3.tendermint.Commit(
    )
  implicit class CommitLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, proto3.tendermint.Commit])
      extends _root_.scalapb.lenses.ObjectLens[UpperPB, proto3.tendermint.Commit](_l) {

    def blockId: _root_.scalapb.lenses.Lens[UpperPB, proto3.tendermint.BlockID] =
      field(_.getBlockId)((c_, f_) => c_.copy(blockId = Option(f_)))

    def optionalBlockId: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[proto3.tendermint.BlockID]] =
      field(_.blockId)((c_, f_) => c_.copy(blockId = f_))

    def precommits: _root_.scalapb.lenses.Lens[UpperPB, _root_.com.google.protobuf.ByteString] =
      field(_.precommits)((c_, f_) => c_.copy(precommits = f_))
  }
  final val BLOCK_ID_FIELD_NUMBER = 1
  final val PRECOMMITS_FIELD_NUMBER = 2
}
