// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package proto3.tendermint

@SerialVersionUID(0L)
final case class EvidenceData(
    evidence: _root_.scala.collection.Seq[proto3.tendermint.Evidence] = _root_.scala.collection.Seq.empty,
    hash: _root_.com.google.protobuf.ByteString = _root_.com.google.protobuf.ByteString.EMPTY
    ) extends scalapb.GeneratedMessage with scalapb.Message[EvidenceData] with scalapb.lenses.Updatable[EvidenceData] {
    @transient
    private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
    private[this] def __computeSerializedValue(): _root_.scala.Int = {
      var __size = 0
      evidence.foreach { __item =>
        val __value = __item
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      }
      
      {
        val __value = hash
        if (__value != _root_.com.google.protobuf.ByteString.EMPTY) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeBytesSize(2, __value)
        }
      };
      __size
    }
    final override def serializedSize: _root_.scala.Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      evidence.foreach { __v =>
        val __m = __v
        _output__.writeTag(1, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      {
        val __v = hash
        if (__v != _root_.com.google.protobuf.ByteString.EMPTY) {
          _output__.writeBytes(2, __v)
        }
      };
    }
    def mergeFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): proto3.tendermint.EvidenceData = {
      val __evidence = (_root_.scala.collection.immutable.Vector.newBuilder[proto3.tendermint.Evidence] ++= this.evidence)
      var __hash = this.hash
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __evidence += _root_.scalapb.LiteParser.readMessage(_input__, proto3.tendermint.Evidence.defaultInstance)
          case 18 =>
            __hash = _input__.readBytes()
          case tag => _input__.skipField(tag)
        }
      }
      proto3.tendermint.EvidenceData(
          evidence = __evidence.result(),
          hash = __hash
      )
    }
    def clearEvidence = copy(evidence = _root_.scala.collection.Seq.empty)
    def addEvidence(__vs: proto3.tendermint.Evidence*): EvidenceData = addAllEvidence(__vs)
    def addAllEvidence(__vs: TraversableOnce[proto3.tendermint.Evidence]): EvidenceData = copy(evidence = evidence ++ __vs)
    def withEvidence(__v: _root_.scala.collection.Seq[proto3.tendermint.Evidence]): EvidenceData = copy(evidence = __v)
    def withHash(__v: _root_.com.google.protobuf.ByteString): EvidenceData = copy(hash = __v)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => evidence
        case 2 => {
          val __t = hash
          if (__t != _root_.com.google.protobuf.ByteString.EMPTY) __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PRepeated(evidence.map(_.toPMessage)(_root_.scala.collection.breakOut))
        case 2 => _root_.scalapb.descriptors.PByteString(hash)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion = proto3.tendermint.EvidenceData
}

object EvidenceData extends scalapb.GeneratedMessageCompanion[proto3.tendermint.EvidenceData] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[proto3.tendermint.EvidenceData] = this
  def fromFieldsMap(__fieldsMap: scala.collection.immutable.Map[_root_.com.google.protobuf.Descriptors.FieldDescriptor, _root_.scala.Any]): proto3.tendermint.EvidenceData = {
    _root_.scala.Predef.require(__fieldsMap.keys.forall(_.getContainingType() == javaDescriptor), "FieldDescriptor does not match message type.")
    val __fields = javaDescriptor.getFields
    proto3.tendermint.EvidenceData(
      __fieldsMap.getOrElse(__fields.get(0), Nil).asInstanceOf[_root_.scala.collection.Seq[proto3.tendermint.Evidence]],
      __fieldsMap.getOrElse(__fields.get(1), _root_.com.google.protobuf.ByteString.EMPTY).asInstanceOf[_root_.com.google.protobuf.ByteString]
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[proto3.tendermint.EvidenceData] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
      proto3.tendermint.EvidenceData(
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.collection.Seq[proto3.tendermint.Evidence]]).getOrElse(_root_.scala.collection.Seq.empty),
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.com.google.protobuf.ByteString]).getOrElse(_root_.com.google.protobuf.ByteString.EMPTY)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = TendermintProto.javaDescriptor.getMessageTypes.get(6)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = TendermintProto.scalaDescriptor.messages(6)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 1 => __out = proto3.tendermint.Evidence
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = proto3.tendermint.EvidenceData(
  )
  implicit class EvidenceDataLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, proto3.tendermint.EvidenceData]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, proto3.tendermint.EvidenceData](_l) {
    def evidence: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.collection.Seq[proto3.tendermint.Evidence]] = field(_.evidence)((c_, f_) => c_.copy(evidence = f_))
    def hash: _root_.scalapb.lenses.Lens[UpperPB, _root_.com.google.protobuf.ByteString] = field(_.hash)((c_, f_) => c_.copy(hash = f_))
  }
  final val EVIDENCE_FIELD_NUMBER = 1
  final val HASH_FIELD_NUMBER = 2
}
