// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package proto3.tendermint

object TendermintProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    com.google.protobuf.timestamp.TimestampProto
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_]] = Seq(
    proto3.tendermint.PartSetHeader,
    proto3.tendermint.BlockID,
    proto3.tendermint.Vote,
    proto3.tendermint.Version,
    proto3.tendermint.Block,
    proto3.tendermint.Commit,
    proto3.tendermint.EvidenceData,
    proto3.tendermint.Evidence,
    proto3.tendermint.Validator
  )
  private lazy val ProtoBytes: Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.Seq(
  """ChB0ZW5kZXJtaW50LnByb3RvEgZwcm90bzMaH2dvb2dsZS9wcm90b2J1Zi90aW1lc3RhbXAucHJvdG8iOQoNUGFydFNldEhlY
  WRlchIUCgV0b3RhbBgBIAEoBVIFdG90YWwSEgoEaGFzaBgCIAEoDFIEaGFzaCJKCgdCbG9ja0lEEhIKBGhhc2gYASABKAxSBGhhc
  2gSKwoFcGFydHMYAiABKAsyFS5wcm90bzMuUGFydFNldEhlYWRlclIFcGFydHMipQIKBFZvdGUSEgoEdHlwZRgBIAEoBVIEdHlwZ
  RIWCgZoZWlnaHQYAiABKANSBmhlaWdodBIUCgVyb3VuZBgDIAEoBVIFcm91bmQSKwoIYmxvY2tfaWQYBCABKAsyDy5wcm90bzMuQ
  mxvY2tJRFIIYmxvY2tfaWQSOAoJdGltZXN0YW1wGAUgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcFIJdGltZXN0YW1wE
  iwKEXZhbGlkYXRvcl9hZGRyZXNzGAYgASgMUhF2YWxpZGF0b3JfYWRkcmVzcxIoCg92YWxpZGF0b3JfaW5kZXgYByABKAVSD3Zhb
  GlkYXRvcl9pbmRleBIcCglzaWduYXR1cmUYCCABKAxSCXNpZ25hdHVyZSIxCgdWZXJzaW9uEhQKBWJsb2NrGAEgASgEUgVibG9ja
  xIQCgNhcHAYAiABKARSA2FwcCLVBQoFQmxvY2sSKQoHdmVyc2lvbhgBIAEoCzIPLnByb3RvMy5WZXJzaW9uUgd2ZXJzaW9uEhkKC
  GNoYWluX2lkGAIgASgJUgdjaGFpbklkEhYKBmhlaWdodBgDIAEoA1IGaGVpZ2h0Ei4KBHRpbWUYBCABKAsyGi5nb29nbGUucHJvd
  G9idWYuVGltZXN0YW1wUgR0aW1lEhcKB251bV90eHMYBSABKANSBm51bVR4cxIbCgl0b3RhbF90eHMYBiABKANSCHRvdGFsVHhzE
  jMKDWxhc3RfYmxvY2tfaWQYByABKAsyDy5wcm90bzMuQmxvY2tJRFILbGFzdEJsb2NrSWQSKAoQbGFzdF9jb21taXRfaGFzaBgII
  AEoDFIObGFzdENvbW1pdEhhc2gSGwoJZGF0YV9oYXNoGAkgASgMUghkYXRhSGFzaBInCg92YWxpZGF0b3JzX2hhc2gYCiABKAxSD
  nZhbGlkYXRvcnNIYXNoEjAKFG5leHRfdmFsaWRhdG9yc19oYXNoGAsgASgMUhJuZXh0VmFsaWRhdG9yc0hhc2gSJQoOY29uc2Vuc
  3VzX2hhc2gYDCABKAxSDWNvbnNlbnN1c0hhc2gSGQoIYXBwX2hhc2gYDSABKAxSB2FwcEhhc2gSKgoRbGFzdF9yZXN1bHRzX2hhc
  2gYDiABKAxSD2xhc3RSZXN1bHRzSGFzaBIjCg1ldmlkZW5jZV9oYXNoGA8gASgMUgxldmlkZW5jZUhhc2gSKQoQcHJvcG9zZXJfY
  WRkcmVzcxgQIAEoDFIPcHJvcG9zZXJBZGRyZXNzEhAKA3R4cxgRIAMoDFIDdHhzEjAKCGV2aWRlbmNlGBIgASgLMhQucHJvdG8zL
  kV2aWRlbmNlRGF0YVIIZXZpZGVuY2USLwoLbGFzdF9jb21taXQYEyABKAsyDi5wcm90bzMuQ29tbWl0UgpsYXN0Q29tbWl0ImIKB
  kNvbW1pdBIqCghibG9ja19pZBgBIAEoCzIPLnByb3RvMy5CbG9ja0lEUgdibG9ja0lkEiwKCnByZWNvbW1pdHMYAiADKAsyDC5wc
  m90bzMuVm90ZVIKcHJlY29tbWl0cyJQCgxFdmlkZW5jZURhdGESLAoIZXZpZGVuY2UYASADKAsyEC5wcm90bzMuRXZpZGVuY2VSC
  GV2aWRlbmNlEhIKBGhhc2gYAiABKAxSBGhhc2gixQEKCEV2aWRlbmNlEhIKBHR5cGUYASABKAlSBHR5cGUSLwoJdmFsaWRhdG9yG
  AIgASgLMhEucHJvdG8zLlZhbGlkYXRvclIJdmFsaWRhdG9yEhYKBmhlaWdodBgDIAEoA1IGaGVpZ2h0Ei4KBHRpbWUYBCABKAsyG
  i5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wUgR0aW1lEiwKEnRvdGFsX3ZvdGluZ19wb3dlchgFIAEoA1IQdG90YWxWb3RpbmdQb
  3dlciI7CglWYWxpZGF0b3ISGAoHYWRkcmVzcxgBIAEoDFIHYWRkcmVzcxIUCgVwb3dlchgDIAEoA1IFcG93ZXJiBnByb3RvMw=="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, Array(
      com.google.protobuf.timestamp.TimestampProto.javaDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}