/*
 * Copyright 2018 Fluence Labs Limited
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package proto3.tendermint

object TendermintProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_]] = Seq(
    proto3.tendermint.PartSetHeader,
    proto3.tendermint.BlockID,
    proto3.tendermint.Timestamp,
    proto3.tendermint.Vote,
    proto3.tendermint.Header,
    proto3.tendermint.Version
  )
  private lazy val ProtoBytes: Array[Byte] =
    scalapb.Encoding.fromBase64(
      scala.collection
        .Seq(
          """ChB0ZW5kZXJtaW50LnByb3RvEgZwcm90bzMiOQoNUGFydFNldEhlYWRlchIUCgV0b3RhbBgBIAEoBVIFdG90YWwSEgoEaGFza
  BgCIAEoDFIEaGFzaCJXCgdCbG9ja0lEEhIKBGhhc2gYASABKAxSBGhhc2gSOAoMcGFydHNfaGVhZGVyGAIgASgLMhUucHJvdG8zL
  lBhcnRTZXRIZWFkZXJSC3BhcnRzSGVhZGVyIjsKCVRpbWVzdGFtcBIYCgdzZWNvbmRzGAEgASgDUgdzZWNvbmRzEhQKBW5hbm9zG
  AIgASgFUgVuYW5vcyKPAgoEVm90ZRISCgR0eXBlGAEgASgFUgR0eXBlEhYKBmhlaWdodBgCIAEoA1IGaGVpZ2h0EhQKBXJvdW5kG
  AMgASgFUgVyb3VuZBIqCghibG9ja19pZBgEIAEoCzIPLnByb3RvMy5CbG9ja0lEUgdibG9ja0lkEiUKBHRpbWUYBSABKAsyES5wc
  m90bzMuVGltZXN0YW1wUgR0aW1lEisKEXZhbGlkYXRvcl9hZGRyZXNzGAYgASgMUhB2YWxpZGF0b3JBZGRyZXNzEicKD3ZhbGlkY
  XRvcl9pbmRleBgHIAEoBVIOdmFsaWRhdG9ySW5kZXgSHAoJc2lnbmF0dXJlGAggASgMUglzaWduYXR1cmUi2AQKBkhlYWRlchIpC
  gd2ZXJzaW9uGAEgASgLMg8ucHJvdG8zLlZlcnNpb25SB3ZlcnNpb24SGQoIY2hhaW5faWQYAiABKAlSB2NoYWluSWQSFgoGaGVpZ
  2h0GAMgASgDUgZoZWlnaHQSJQoEdGltZRgEIAEoCzIRLnByb3RvMy5UaW1lc3RhbXBSBHRpbWUSFwoHbnVtX3R4cxgFIAEoA1IGb
  nVtVHhzEhsKCXRvdGFsX3R4cxgGIAEoA1IIdG90YWxUeHMSMwoNbGFzdF9ibG9ja19pZBgHIAEoCzIPLnByb3RvMy5CbG9ja0lEU
  gtsYXN0QmxvY2tJZBIoChBsYXN0X2NvbW1pdF9oYXNoGAggASgMUg5sYXN0Q29tbWl0SGFzaBIbCglkYXRhX2hhc2gYCSABKAxSC
  GRhdGFIYXNoEicKD3ZhbGlkYXRvcnNfaGFzaBgKIAEoDFIOdmFsaWRhdG9yc0hhc2gSMAoUbmV4dF92YWxpZGF0b3JzX2hhc2gYC
  yABKAxSEm5leHRWYWxpZGF0b3JzSGFzaBIlCg5jb25zZW5zdXNfaGFzaBgMIAEoDFINY29uc2Vuc3VzSGFzaBIZCghhcHBfaGFza
  BgNIAEoDFIHYXBwSGFzaBIqChFsYXN0X3Jlc3VsdHNfaGFzaBgOIAEoDFIPbGFzdFJlc3VsdHNIYXNoEiMKDWV2aWRlbmNlX2hhc
  2gYDyABKAxSDGV2aWRlbmNlSGFzaBIpChBwcm9wb3Nlcl9hZGRyZXNzGBAgASgMUg9wcm9wb3NlckFkZHJlc3MiMQoHVmVyc2lvb
  hIUCgVCbG9jaxgBIAEoBFIFQmxvY2sSEAoDQXBwGAIgASgEUgNBcHBiBnByb3RvMw=="""
        )
        .mkString
    )
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(
      javaProto,
      Array(
        )
    )
  }

  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}
