// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package proto3.tendermint

object TendermintProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_]] = Seq(
    proto3.tendermint.PartSetHeader,
    proto3.tendermint.BlockID,
    proto3.tendermint.Timestamp,
    proto3.tendermint.Vote,
    proto3.tendermint.Header,
    proto3.tendermint.Version
  )
  private lazy val ProtoBytes: Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.Seq(
  """ChB0ZW5kZXJtaW50LnByb3RvEgZwcm90bzMiOQoNUGFydFNldEhlYWRlchIUCgVUb3RhbBgBIAEoBVIFVG90YWwSEgoESGFza
  BgCIAEoDFIESGFzaCJWCgdCbG9ja0lEEhIKBEhhc2gYASABKAxSBEhhc2gSNwoLUGFydHNIZWFkZXIYAiABKAsyFS5wcm90bzMuU
  GFydFNldEhlYWRlclILUGFydHNIZWFkZXIiOwoJVGltZXN0YW1wEhgKB3NlY29uZHMYASABKANSB3NlY29uZHMSFAoFbmFub3MYA
  iABKAVSBW5hbm9zIowCCgRWb3RlEhIKBFR5cGUYASABKAVSBFR5cGUSFgoGSGVpZ2h0GAIgASgDUgZIZWlnaHQSFAoFUm91bmQYA
  yABKAVSBVJvdW5kEikKB0Jsb2NrSUQYBCABKAsyDy5wcm90bzMuQmxvY2tJRFIHQmxvY2tJRBIlCgR0aW1lGAUgASgLMhEucHJvd
  G8zLlRpbWVzdGFtcFIEdGltZRIqChBWYWxpZGF0b3JBZGRyZXNzGAYgASgMUhBWYWxpZGF0b3JBZGRyZXNzEiYKDlZhbGlkYXRvc
  kluZGV4GAcgASgFUg5WYWxpZGF0b3JJbmRleBIcCglTaWduYXR1cmUYCCABKAxSCVNpZ25hdHVyZSLHBAoGSGVhZGVyEikKB1Zlc
  nNpb24YASABKAsyDy5wcm90bzMuVmVyc2lvblIHVmVyc2lvbhIYCgdDaGFpbklEGAIgASgJUgdDaGFpbklEEhYKBkhlaWdodBgDI
  AEoA1IGSGVpZ2h0EiUKBFRpbWUYBCABKAsyES5wcm90bzMuVGltZXN0YW1wUgRUaW1lEhYKBk51bVR4cxgFIAEoA1IGTnVtVHhzE
  hoKCFRvdGFsVHhzGAYgASgDUghUb3RhbFR4cxIxCgtMYXN0QmxvY2tJRBgHIAEoCzIPLnByb3RvMy5CbG9ja0lEUgtMYXN0QmxvY
  2tJRBImCg5MYXN0Q29tbWl0SGFzaBgIIAEoDFIOTGFzdENvbW1pdEhhc2gSGgoIRGF0YUhhc2gYCSABKAxSCERhdGFIYXNoEiYKD
  lZhbGlkYXRvcnNIYXNoGAogASgMUg5WYWxpZGF0b3JzSGFzaBIuChJOZXh0VmFsaWRhdG9yc0hhc2gYCyABKAxSEk5leHRWYWxpZ
  GF0b3JzSGFzaBIkCg1Db25zZW5zdXNIYXNoGAwgASgMUg1Db25zZW5zdXNIYXNoEhgKB0FwcEhhc2gYDSABKAxSB0FwcEhhc2gSK
  AoPTGFzdFJlc3VsdHNIYXNoGA4gASgMUg9MYXN0UmVzdWx0c0hhc2gSIgoMRXZpZGVuY2VIYXNoGA8gASgMUgxFdmlkZW5jZUhhc
  2gSKAoPUHJvcG9zZXJBZGRyZXNzGBAgASgMUg9Qcm9wb3NlckFkZHJlc3MiMQoHVmVyc2lvbhIUCgVCbG9jaxgBIAEoBFIFQmxvY
  2sSEAoDQXBwGAIgASgEUgNBcHBiBnByb3RvMw=="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}