{
 "title": "Fluence local cluster monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Commit and txs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "worker_delivertx_count{instance=~\".*host.docker.internal.*\"}",
     "legendFormat": "Txs {{instance}}"
    },
    {
     "expr": "worker_commit_count{instance=~\".*host.docker.internal.*\"}",
     "legendFormat": "Commits {{instance}}"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "worker_query_count{instance=~\".*host.docker.internal.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Avg CheckTx latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "  rate(worker_checktx_latency_sum{instance=~\".*host.docker.internal.*\"}[1m])\n/\n  rate(worker_checktx_count{instance=~\".*host.docker.internal.*\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Avg DeliverTx latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "  rate(worker_delivertx_latency_sum{instance=~\".*host.docker.internal.*\"}[1m])\n/\n  rate(worker_delivertx_count{instance=~\".*host.docker.internal.*\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Avg CheckTx validation time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "  rate(worker_checktx_validation_time_sum{instance=~\".*host.docker.internal.*\"}[1m])\n/\n  rate(worker_checktx_count{instance=~\".*host.docker.internal.*\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Avg DeliverTx validation time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "  rate(worker_delivertx_validation_time_sum{instance=~\".*host.docker.internal.*\"}[1m])\n/\n  rate(worker_delivertx_count{instance=~\".*host.docker.internal.*\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Avg VM invocation time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "  rate(worker_vm_invoke_time_sum{instance=~\".*host.docker.internal.*\"}[1m])\n/\n  rate(worker_vm_invoke_counter{instance=~\".*host.docker.internal.*\"}[1m])",
     "legendFormat": "{{method}} {{instance}}"
    }
   ]
  },
  {
   "title": "Avg Query processing time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "  rate(worker_query_process_time_sum{instance=~\".*host.docker.internal.*\"}[1m])\n/\n  rate(worker_query_count{instance=~\".*host.docker.internal.*\"}[1m])",
     "legendFormat": "{{method}} {{instance}}"
    }
   ]
  }
 ]
}