(function() {var implementors = {
"aquamarine":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"aquamarine/enum.DataStoreError.html\" title=\"enum aquamarine::DataStoreError\">DataStoreError</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"aquamarine/enum.AquamarineApiError.html\" title=\"enum aquamarine::AquamarineApiError\">AquamarineApiError</a>"]],
"chain_connector":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"chain_connector/enum.ConnectorError.html\" title=\"enum chain_connector::ConnectorError\">ConnectorError</a>"]],
"chain_data":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"chain_data/enum.ChainDataError.html\" title=\"enum chain_data::ChainDataError\">ChainDataError</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"chain_data/enum.LogParseError.html\" title=\"enum chain_data::LogParseError\">LogParseError</a>"]],
"core_manager":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"core_manager/errors/enum.CreateError.html\" title=\"enum core_manager::errors::CreateError\">CreateError</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"core_manager/errors/enum.LoadingError.html\" title=\"enum core_manager::errors::LoadingError\">LoadingError</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"core_manager/errors/enum.AcquireError.html\" title=\"enum core_manager::errors::AcquireError\">AcquireError</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"core_manager/errors/enum.PersistError.html\" title=\"enum core_manager::errors::PersistError\">PersistError</a>"]],
"fs_utils":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"fs_utils/enum.LoadDataError.html\" title=\"enum fs_utils::LoadDataError\">LoadDataError</a>"]],
"kademlia":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"kademlia/enum.KademliaError.html\" title=\"enum kademlia::KademliaError\">KademliaError</a>"]],
"particle_args":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"particle_args/enum.ArgsError.html\" title=\"enum particle_args::ArgsError\">ArgsError</a>"]],
"particle_execution":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"particle_execution/enum.VaultError.html\" title=\"enum particle_execution::VaultError\">VaultError</a>"]],
"particle_modules":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"particle_modules/enum.ModuleError.html\" title=\"enum particle_modules::ModuleError\">ModuleError</a>"]],
"particle_protocol":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"particle_protocol/enum.ParticleError.html\" title=\"enum particle_protocol::ParticleError\">ParticleError</a>"]],
"particle_services":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"particle_services/enum.ServiceError.html\" title=\"enum particle_services::ServiceError\">ServiceError</a>"]],
"spell_event_bus":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"spell_event_bus/api/enum.ConfigError.html\" title=\"enum spell_event_bus::api::ConfigError\">ConfigError</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"spell_event_bus/api/enum.EventBusError.html\" title=\"enum spell_event_bus::api::EventBusError\">EventBusError</a>"]],
"spell_service_api":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"spell_service_api/enum.CallError.html\" title=\"enum spell_service_api::CallError\">CallError</a>"]],
"workers":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"workers/enum.KeyStorageError.html\" title=\"enum workers::KeyStorageError\">KeyStorageError</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/error/trait.Error.html\" title=\"trait core::error::Error\">Error</a> for <a class=\"enum\" href=\"workers/enum.WorkersError.html\" title=\"enum workers::WorkersError\">WorkersError</a>"]]
};if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()