// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package proto3.block

object BlockProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_]] = Seq(
    proto3.block.PartSetHeader,
    proto3.block.BlockID,
    proto3.block.Header,
    proto3.block.Version,
    proto3.block.Timestamp
  )
  private lazy val ProtoBytes: Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.Seq(
  """CgtibG9jay5wcm90bxIGcHJvdG8zIjkKDVBhcnRTZXRIZWFkZXISFAoFVG90YWwYASABKAVSBVRvdGFsEhIKBEhhc2gYAiABK
  AxSBEhhc2giVgoHQmxvY2tJRBISCgRIYXNoGAEgASgMUgRIYXNoEjcKC1BhcnRzSGVhZGVyGAIgASgLMhUucHJvdG8zLlBhcnRTZ
  XRIZWFkZXJSC1BhcnRzSGVhZGVyIscECgZIZWFkZXISKQoHVmVyc2lvbhgBIAEoCzIPLnByb3RvMy5WZXJzaW9uUgdWZXJzaW9uE
  hgKB0NoYWluSUQYAiABKAlSB0NoYWluSUQSFgoGSGVpZ2h0GAMgASgDUgZIZWlnaHQSJQoEVGltZRgEIAEoCzIRLnByb3RvMy5Ua
  W1lc3RhbXBSBFRpbWUSFgoGTnVtVHhzGAUgASgDUgZOdW1UeHMSGgoIVG90YWxUeHMYBiABKANSCFRvdGFsVHhzEjEKC0xhc3RCb
  G9ja0lEGAcgASgLMg8ucHJvdG8zLkJsb2NrSURSC0xhc3RCbG9ja0lEEiYKDkxhc3RDb21taXRIYXNoGAggASgMUg5MYXN0Q29tb
  Wl0SGFzaBIaCghEYXRhSGFzaBgJIAEoDFIIRGF0YUhhc2gSJgoOVmFsaWRhdG9yc0hhc2gYCiABKAxSDlZhbGlkYXRvcnNIYXNoE
  i4KEk5leHRWYWxpZGF0b3JzSGFzaBgLIAEoDFISTmV4dFZhbGlkYXRvcnNIYXNoEiQKDUNvbnNlbnN1c0hhc2gYDCABKAxSDUNvb
  nNlbnN1c0hhc2gSGAoHQXBwSGFzaBgNIAEoDFIHQXBwSGFzaBIoCg9MYXN0UmVzdWx0c0hhc2gYDiABKAxSD0xhc3RSZXN1bHRzS
  GFzaBIiCgxFdmlkZW5jZUhhc2gYDyABKAxSDEV2aWRlbmNlSGFzaBIoCg9Qcm9wb3NlckFkZHJlc3MYECABKAxSD1Byb3Bvc2VyQ
  WRkcmVzcyIxCgdWZXJzaW9uEhQKBUJsb2NrGAEgASgEUgVCbG9jaxIQCgNBcHAYAiABKARSA0FwcCI7CglUaW1lc3RhbXASGAoHc
  2Vjb25kcxgBIAEoA1IHc2Vjb25kcxIUCgVuYW5vcxgCIAEoBVIFbmFub3NiBnByb3RvMw=="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}