/*
 * Copyright 2018 Fluence Labs Limited
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
mod settings;

extern crate rand;
extern crate rand_isaac;

use rand::{Rng, SeedableRng};
use rand_isaac::IsaacRng;
use settings::*;

/// generates random matrix with given size by IsaacRng
fn generate_random_matrix(rows_number: u32, columns_count: u32, seed: u64) -> Matrix {
    let mut rng: IsaacRng = SeedableRng::seed_from_u64(seed);
    Matrix::from_fn(rows_number as usize, columns_count as usize,
                    |_, _| rng.gen_range(0u64, GENERATION_INTERVAL))
}

/// computes hash of a matrix as its trace
fn compute_matrix_hash(matrix: &Matrix) -> u64 {
    let mut trace : u64 = 0;

    // it is assumed that matrix is squared
    for i in 0..matrix.ncols() {
        trace += matrix[(i,i)]
    }

    trace
}

/// This test computes QR decomposition of randomly generated by IsaacRng square matrices of
/// MATRIX_SIZE. There are ITERATIONS_COUNT iterations of decompositions. On each iteration a new
/// matrices is generated by seed that computed as a xor of singular values of previously matrix
/// decomposition result. And as the first seed SEED parameter is used.
///
/// Returns a final matrix_hash to prevent possible aggressive optimization.
#[no_mangle]
pub extern "C" fn main() -> u64 {
    let matrix_size : u32 = MATRIX_SIZE.parse::<u32>().unwrap();
    let seed : u64 = SEED.parse::<u64>().unwrap();
    let iterations_count : u64 = ITERATIONS_COUNT.parse::<u64>().unwrap();

    let mut matrix_hash : u64 = seed;
    for _ in 1..iterations_count {
        let matrix_a = generate_random_matrix(matrix_size, matrix_size, matrix_hash);
        matrix_hash = compute_matrix_hash(&matrix_a);
        let matrix_b = generate_random_matrix(matrix_size, matrix_size, matrix_hash);

        let matrix_c = matrix_a * matrix_b;
        matrix_hash = compute_matrix_hash(&matrix_c);
    }

    matrix_hash
}
